title: Eyes Blue Docs
description: 記錄各個專案的建置流程、設定步驟與開發筆記
theme: just-the-docs

lang: zh-TW
color_scheme: light
search_enabled: true
heading_anchors: true

back_to_top: true
back_to_top_text: 回到頁首
footer_content: "Copyright &copy; 2026 Eyes Blue Docs."
