title: 紀念日計算器
description: 紀念日計算器的使用說明與最新資訊
theme: just-the-docs

lang: zh-TW
color_scheme: light
search_enabled: true
heading_anchors: true

back_to_top: true
back_to_top_text: 回到頁首
footer_content: "Copyright &copy; 2026 紀念日計算器。"

